/*
 * KEYPAD_FUNCTION.h
 *
 * Created: 2/13/2024 2:00:46 PM
 *  Author: Mohamed
 */ 


#ifndef KEYPAD_FUNCTION_H_
#define KEYPAD_FUNCTION_H_
#include "STD_DIO.h"
#include "DIO_FINCTION.h"
//ROWS PINS
#define KEYPAD_ROW4 DIO_PINC0      
#define KEYPAD_ROW3 DIO_PINC1 
#define KEYPAD_ROW2 DIO_PINC2 
#define KEYPAD_ROW1 DIO_PINC3 
//COLOUMS PINS
#define KEYPAD_COLOUM1 DIO_PINC4 
#define KEYPAD_COLOUM2 DIO_PINC5 
#define KEYPAD_COLOUM3 DIO_PINC6 
#define KEYPAD_COLOUM4 DIO_PINC7 
//ROW 1
#define KEYPAD_ROW1_COLOUM1 'c'
#define KEYPAD_ROW1_COLOUM2 '0'
#define KEYPAD_ROW1_COLOUM3 '='
#define KEYPAD_ROW1_COLOUM4 '+'
//ROW 2
#define KEYPAD_ROW2_COLOUM1 '1'
#define KEYPAD_ROW2_COLOUM2 '2'
#define KEYPAD_ROW2_COLOUM3 '3'
#define KEYPAD_ROW2_COLOUM4 '-'
//ROW 3
#define KEYPAD_ROW3_COLOUM1 '4'
#define KEYPAD_ROW3_COLOUM2 '5'
#define KEYPAD_ROW3_COLOUM3 '6'
#define KEYPAD_ROW3_COLOUM4 '*'
//ROW 4
#define KEYPAD_ROW4_COLOUM1 '7'
#define KEYPAD_ROW4_COLOUM2 '8'
#define KEYPAD_ROW4_COLOUM3 '9'
#define KEYPAD_ROW4_COLOUM4 '/'

#define KEYPAD_UNPRISD 'X'
//FUNCTION
void KEYPAD_INIT();
u8 KEYPAD_READ(void);
#endif /* KEYPAD_FUNCTION_H_ */