/*
 * SEVEN_SEGMENT.h
 *
 * Created: 2/8/2024 1:38:04 PM
 *  Author: Mohamed
 */ 


#ifndef SEVEN_SEGMENT_H_
#define SEVEN_SEGMENT_H_
#include "DIO_FINCTION.h"
#include "BIT_MATH.h"

#define SEVEN_SEGMENT1_ENABLE     DIO_PINC6
#define SEVEN_SEGMENT2_ENABLE     DIO_PINC7

#define SEVEN_SEGMENT_PIN0         DIO_PINC0
#define SEVEN_SEGMENT_PIN1         DIO_PINC1
#define SEVEN_SEGMENT_PIN2         DIO_PINC2
#define SEVEN_SEGMENT_PIN3         DIO_PINC3

void SEVEN_SEGMENT_INIT(void);
void SEVEN_SEGMENT_WRITE_SINGLE(u8,u8);
void SEVEN_SEGMENT_WRITE_DOUBLE(u8);

#define ENABLE_SEVEN_SEGMENT1      DIO_SIT_BIT_VALUO(SEVEN_SEGMENT1_ENABLE,LOW)
#define DESABLE_SEVEN_SEGMENT1     DIO_SIT_BIT_VALUO(SEVEN_SEGMENT1_ENABLE,HIGH)
    
#define ENABLE_SEVEN_SEGMENT2      DIO_SIT_BIT_VALUO(SEVEN_SEGMENT2_ENABLE,LOW)
#define DESABLE_SEVEN_SEGMENT2     DIO_SIT_BIT_VALUO(SEVEN_SEGMENT2_ENABLE,HIGH)    

#define SEGMENT_NUMBER1 0
#define SEGMENT_NUMBER2 1


#endif /* SEVEN_SEGMENT_H_ */