/*
 * SEVEN_SEGMENT.c
 *
 * Created: 2/8/2024 2:56:30 PM
 *  Author: Mohamed
 */ 
#define F_CPU 16000000
#include "SEVEN_SEGMENT.h"
#include "util/delay.h"
// TO INIT THE DIRICTION OF 7-SEGMENT PIN
void SEVEN_SEGMENT_INIT(void)
{
	DIO_SIT_BIT_DIRICTION(SEVEN_SEGMENT1_ENABLE,OUTPUT);
	DIO_SIT_BIT_DIRICTION(SEVEN_SEGMENT2_ENABLE,OUTPUT);
	
	DIO_SIT_BIT_DIRICTION(SEVEN_SEGMENT_PIN0,OUTPUT);
	DIO_SIT_BIT_DIRICTION(SEVEN_SEGMENT_PIN1,OUTPUT);
	DIO_SIT_BIT_DIRICTION(SEVEN_SEGMENT_PIN2,OUTPUT);
	DIO_SIT_BIT_DIRICTION(SEVEN_SEGMENT_PIN3,OUTPUT);
}
void SEVEN_SEGMENT_WRITE_SINGLE(u8 NUMBER,u8 SEGMENT_NUMBER)
{
	//NUMBER IS THE NUMBER NEED TO WRITE IT 
	if (SEGMENT_NUMBER==SEGMENT_NUMBER1)
	{
		ENABLE_SEVEN_SEGMENT1;
		DESABLE_SEVEN_SEGMENT2;
	} 
	else if(SEGMENT_NUMBER==SEGMENT_NUMBER2)
	{
		ENABLE_SEVEN_SEGMENT2;
		DESABLE_SEVEN_SEGMENT1;
	}
	DIO_SIT_BIT_VALUO(SEVEN_SEGMENT_PIN0,(GET_BIT(NUMBER,0)));
	DIO_SIT_BIT_VALUO(SEVEN_SEGMENT_PIN1,(GET_BIT(NUMBER,1)));
	DIO_SIT_BIT_VALUO(SEVEN_SEGMENT_PIN2,(GET_BIT(NUMBER,2)));
	DIO_SIT_BIT_VALUO(SEVEN_SEGMENT_PIN3,(GET_BIT(NUMBER,3)));
	_delay_ms(50);
}
void SEVEN_SEGMENT_WRITE_DOUBLE(u8 NUMBER)
{
	u8 tens=NUMBER/10;
	u8 ones=NUMBER%10;
	SEVEN_SEGMENT_WRITE_SINGLE(ones,SEGMENT_NUMBER1);
	SEVEN_SEGMENT_WRITE_SINGLE(tens,SEGMENT_NUMBER2);
}