/*
 * EXTERNAL_INTERRAPT_FUNCTION.c
 *
 * Created: 2/16/2024 8:36:19 PM
 *  Author: Mohamed
 */
#define F_CPU 16000000
#include "BIT_MATH.h"
#include "util/delay.h"
#include "DIO_FINCTION.h"
#include "STD_DIO.h"
#include "STD_TYPEDEF.h"
#include "INTERRUPT_ADRESSES.h" 
#include "EXTERNAL_ENTERRAPT_FUNCTIONS.h"
#include "GENERAL_INTERRAPT.h"
void EXTERNAL_ETERRAPT_ENABLE(u8 EXTERNAL_INTERRAPT_NUMBER,u8 EXTERNAL_INTERRAPT_SEGMAL)
{
	GENERAL_INTERRAPT_ENABLE;
	//EXTERNAL INTERRAPT0
	if (EXTERNAL_INTERRAPT_NUMBER==EXTERNAL_INTERRAPT0)
	{
		EXTERNAL_INTERRAPT0_ENABLE;
		if (EXTERNAL_INTERRAPT_SEGMAL==EXTERNAL_INTERRAPTINPUT_LOW_LEVEL)
		{
			RESET_BIT(MCUCR,ISC00);
			RESET_BIT(MCUCR,ISC01);
		}
		else if (EXTERNAL_INTERRAPT_SEGMAL==EXTERNAL_INTERRAPTINPUT_ANY_lOGESTIC_CHANGE)
		{
			SET_BIT(MCUCR,ISC00);
			RESET_BIT(MCUCR,ISC01);
		}
		else if (EXTERNAL_INTERRAPT_SEGMAL==EXTERNAL_INTERRAPTINPUT_FALLING_EDGE)
		{
			RESET_BIT(MCUCR,ISC00);
			SET_BIT(MCUCR,ISC01);
		}
		else if(EXTERNAL_INTERRAPT_SEGMAL==EXTERNAL_INTERRAPTINPUT_RISING_EDGE)
		{
			SET_BIT(MCUCR,ISC00);
			SET_BIT(MCUCR,ISC01);
		}
	}
	//EXTERNAL INTERRAPT 1
	else if (EXTERNAL_INTERRAPT_NUMBER==EXTERNAL_INTERRAPT1)
	{
		EXTERNAL_INTERRAPT1_ENABLE;
		if (EXTERNAL_INTERRAPT_SEGMAL==EXTERNAL_INTERRAPTINPUT_LOW_LEVEL)
		{
			RESET_BIT(MCUCR,ISC10);
			RESET_BIT(MCUCR,ISC11);
		}
		else if (EXTERNAL_INTERRAPT_SEGMAL==EXTERNAL_INTERRAPTINPUT_ANY_lOGESTIC_CHANGE)
		{
			SET_BIT(MCUCR,ISC10);
			RESET_BIT(MCUCR,ISC11);
		}
		else if (EXTERNAL_INTERRAPT_SEGMAL==EXTERNAL_INTERRAPTINPUT_FALLING_EDGE)
		{
			RESET_BIT(MCUCR,ISC10);
			SET_BIT(MCUCR,ISC11);
		}
		else if(EXTERNAL_INTERRAPT_SEGMAL==EXTERNAL_INTERRAPTINPUT_RISING_EDGE)
		{
			SET_BIT(MCUCR,ISC10);
			SET_BIT(MCUCR,ISC11);
		}
	}
	//EXTERNALINTERRAPT2
	else if (EXTERNAL_INTERRAPT_NUMBER==EXTERNAL_INTERRAPT2)
	{
		EXTERNAL_INTERRAPT2_ENABLE;
		if (EXTERNAL_INTERRAPT_SEGMAL==EXTERNAL_INTERRAPTINPUT_FALLING_EDGE)
		{
			RESET_BIT(MCUCSR,ISC2);
		}
		else if(EXTERNAL_INTERRAPT_SEGMAL==EXTERNAL_INTERRAPTINPUT_RISING_EDGE)
		{
			SET_BIT(MCUCSR,ISC2);
		}
	}
}
