/*
 * EXTERNAL_ENTERRAPT_FUNCTIONS.h
 *
 * Created: 2/16/2024 8:35:16 PM
 *  Author: Mohamed
 */ 


#ifndef EXTERNAL_ENTERRAPT_FUNCTIONS_H_
#define EXTERNAL_ENTERRAPT_FUNCTIONS_H_

//TO CHOOSE THE EXTERNALINTERRAPT
#define EXTERNAL_INTERRAPT0 0
#define EXTERNAL_INTERRAPT1 1
#define EXTERNAL_INTERRAPT2 2

//TO COTROL IN EXTERNAL ENTERRAPT
//ENABLE
#define EXTERNAL_INTERRAPT0_ENABLE  SET_BIT(GICR,INT0) 
#define EXTERNAL_INTERRAPT1_ENABLE  SET_BIT(GICR,INT1)
#define EXTERNAL_INTERRAPT2_ENABLE  SET_BIT(GICR,INT2)
//DESABLE
#define EXTERNAL_INTERRAPT0_DESABLE READ_BITE(GICR,INT0)
#define EXTERNAL_INTERRAPT1_DESABLE READ_BITE(GICR,INT1)
#define EXTERNAL_INTERRAPT2_DESABLE READ_BITE(GICR,INT2)
// TYPE OF EXTERNAL INTERRAPT SEGNAL CONTROL(MCUCR,MCUCSR)
#define EXTERNAL_INTERRAPTINPUT_LOW_LEVEL 0
#define EXTERNAL_INTERRAPTINPUT_ANY_lOGESTIC_CHANGE 1
#define EXTERNAL_INTERRAPTINPUT_FALLING_EDGE 2
#define EXTERNAL_INTERRAPTINPUT_RISING_EDGE 3
//MCUCR PINS
#define ISC00 0
#define ISC01 1
#define ISC10 2
#define ISC11 3
//MCUCSR PINS
#define ISC2 6
//GICR PINS
#define INT1 7
#define INT0 6
#define INT2 5

//THE FUNCTION
void EXTERNAL_ETERRAPT_ENABLE(u8,u8);
#endif /* EXTERNAL_ENTERRAPT_FUNCTIONS_H_ */