/*
 * INTERRUPT_ADRESSES.h
 *
 * Created: 2/16/2024 7:46:44 PM
 *  Author: Mohamed
 */ 


#ifndef INTERRUPT_ADRESSES_H_
#define INTERRUPT_ADRESSES_H_

#define SREG *(volatile u8*)0x5F  //TO ACTIVTE THE INTERRAPT
#define MCUCR *(volatile u8*)0x55  //TO CHOOSE THE TYPE OF INPUT EXTERNAL INTERRAPT OF INTRRAPT0 INTRRAPT1
#define MCUCSR *(volatile u8*)0x54 //TO CHOOSE THE TYPE OF INPUT EXTERNAL INTERRAPT OF INTRRAPT2
#define GICR *(volatile u8*)0x5B   //TO ENABLE THE EXTERNAL INTERRAPT 0 1 2

#endif /* INTERRUPT_ADRESSES_H_ */